# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-22 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='type_of_art',
            field=models.CharField(default=datetime.datetime(2017, 4, 22, 19, 59, 43, 642812, tzinfo=utc), max_length=255, verbose_name='\u0422\u0438\u043f'),
            preserve_default=False,
        ),
    ]
